site_name: coverage-reporter

# Repository information
repo_name: "codacy/codacy-coverage-reporter"
repo_url: "https://github.com/codacy/codacy-coverage-reporter"
edit_uri: "edit/master/docs/"

strict: true

theme:
  name: "material"

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - "index.md"
  - "alternative-ways-of-running-coverage-reporter.md"
  - "troubleshooting-common-issues.md"
